# Generated by Django 3.1.5 on 2021-01-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_picture', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Файл')),
            ],
        ),
    ]
